version: 0.2
phases:
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo post_build
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar
#web: java -Dfile.encoding=UTF-8 -Xms2g -Xmx2g -jar ahp-0.0.1-SNAPSHOT.jar
#artifacts:
#  files:
#    - '**/*'
#server:
#  port: 5000
#cloud:
#  aws:
#    region:
#      static: N. Virginia
